FROM python:3.13.11-alpine

WORKDIR /build

COPY ./backend/requirements.txt .
RUN apk add --no-cache gcc clang
RUN pip install --no-cache-dir -r requirements.txt

RUN apk add --no-cache curl jq
COPY ./backend/.env_example .

WORKDIR /app

COPY --exclude=uploads \
    --exclude=.gitignore \
    --exclude=requirements.txt \
    --exclude=.env_example \
    --exclude=.venv \
    ./backend/ .

COPY ./docker/api/entrypoint.sh .
RUN chmod +x ./entrypoint.sh

EXPOSE 8000/tcp

VOLUME ["/uploads"]
VOLUME ["/config"]

ENV ENV_FILE=/config/.env
ENV UVICORN_HOST=0.0.0.0
ENV UVICORN_PORT=8000

ENTRYPOINT ["/app/entrypoint.sh", "uvicorn"]
CMD ["app.main:app", "--reload"] 