"""Add image fields to messages

Revision ID: c392bc59c1f7
Revises: cacf0c7ac60c
Create Date: 2025-12-05 21:38:08.704600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c392bc59c1f7'
down_revision: Union[str, None] = 'cacf0c7ac60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('has_image', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('image_size', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('image_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_type')
    op.drop_column('messages', 'image_size')
    op.drop_column('messages', 'image_filename')
    op.drop_column('messages', 'image_path')
    op.drop_column('messages', 'has_image')
    # ### end Alembic commands ###
